apiVersion: v1
kind: file
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- $file := .Files }}
  {{- range tuple "config1.toml" "config2.toml" "config3.toml" }}
  {{ . }}: |-
    {{ $file.Get . }}
  {{- end }}

# Glob patterns 通过匹配获取文件
{{ (.Files.Glob "*.toml").AsConfig | indent 2 }}

# Encoding
  token: |-
     {{ .Files.Get "config1.toml" | b64enc }}

# lines
  some-file.txt: {{ range .Files.Lines "foo/bar.txt" }}
    {{ . }}
    {{- end }}

