apiVersion: v1
kind: Value
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  # 外层给 .Release.Name设置对应变量为$relname
  {{- $relname := .Release.Name -}}

  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  # 在with阶段获取变量$relname
  release: {{ $relname }}
  {{- end }}

  # range index
  toppings:
    {{- range $index, $value := .Values.pizzaToppings }}
    {{ $index }}: {{ $value }}
    {{- end }}
  kv:
  {{- range $key, $value := .Values.favoriteDrink }}
    {{ $key }}: {{ $value }}
  {{- end }}
