apiVersion: v1
kind: Pod
metadata:
  name: command-demo-2
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: busybox
    env:
      - name: MESSAGE
        value: "hello world"
    command: ["echo"]
    args: ["$(MESSAGE)"]
  restartPolicy: OnFailure
