apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  volumes:
  - name: workdir
    emptyDir: {}
  initContainers:
  - name: install
    image: busybox
    command:
    #- touch
    #- "/work-dir/index.html"
    - /bin/sh
    - -c
    - 'echo 123 > /work-dir/index.html'
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
