apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["/bin/sh", "-c", "env"]
    env:
      - name: BR_WHO
        valueFrom:
          configMapKeyRef:
            name: special-config-2
            key: RB_USER
  restartPolicy: Never
